### ISSUE TITLE
Instructions

### ISSUE THREAD

**Issue by coolpalani** [scholzj/aws-k8s-kops-ansible#11]
Hello,

Could you bit explain how should i want initiate this playbook for create Kubernate cluster in AWS?

Should I want manually create one instance in AWS and provide instance ip address in ansible inventory for install kops,cubectl or your playbook will automatically take care to create that base instance also? 
ideally master node and worker node will be create during cluster create

Since I am not seeing any where you were define about aws access key and secret key for access AWS

**Comment by scholzj** [comment]
Hi @coolpalani ,

I always run it from my local PC (Mac or Linux - I don't have Windows, so I never tried it there). I install Ansible first and then I use it to install Kops (`ansible-playbook install-kops.yaml`) and Kubectl (`ansible-playbook install-kubectl.yaml`).

Once I have the prerequisites I export the AWS credentials as env. variables:
```
export AWS_ACCESS_KEY_ID="XXX"
export AWS_SECRET_ACCESS_KEY="XXX"
```

And I create the S3 store:
```
ansible-playbook create-state-store.yaml
```

and deploy the cluster:
```
ansible-playbook create.yaml
```

---

You can do the deployment from an AWS machine. But in that case you should create the AWS machine and than run the Ansible playbook directly from this machine and not from your local PC against the AWS machine. 

But the only reason I would see for this is if you cannot install Ansible / Kops / Kubectl on your local PC. Otherwise this should not be needed.

--- 

In general agree that these things might not be clear from the README file. I will have a look at it and try to update it.

**Comment by coolpalani** [comment]
Hello @scholzj 

Thank you very much for explained.
I will start initiate deployment.

**Comment by scholzj** [comment]
I updated the `README.md` file to make the installation and deletion process a bit more clear. Feel free to have a look and let me know if you think it is better now.

**Comment by coolpalani** [comment]
Hello @scholzj

I have registered one domain in godaddy and created zones in AWS route 53.
I updated nameservers in godaddy.
But I couldn't access kubernetes dashboard.
Could you tell me which url should I want hit for access kubernetes dashboard

**Comment by scholzj** [comment]
The dashboard isn't exposed through loadbalancer by default (because it would cost money and because it would be insecure). 

The way I access it is that I run `kubectl proxy` on my localhost - this exposes the services running in the Kubernetes cluster on `127.0.0.1:8001` - so once the `kubectl proxy` is running you can just open your browser and go to `127.0.0.1:8001/ui` - and that redirects you into the dashboard.

**Comment by scholzj** [comment]
FYI: I added a new FAQ section and described this in there.

**Comment by coolpalani** [comment]
@scholzj 
Great!
I had been completed the deployment and able to reach the dashboard.
if we add one or two scenario use cases such as wordpress, CI/CD playbook on top of this kubernetes, it would be helpful.
I had already done this use cases deployment in OpenShift platform, but I am wondering to try in Kubernetes cluster. :)
