### ISSUE TITLE
External endpoint isn't creating

### ISSUE THREAD

**Issue by coolpalani** [scholzj/aws-k8s-kops-ansible#17]
When I deploy this micros service demo application using this repo https://github.com/microservices-demo/microservices-demo , end-pint isn't creating for accessing the sock shop front end ui.

steps:

git clone https://github.com/microservices-demo/microservices-demo.git
cd deploy/kubernetes
kubectl apply -f manifests/sock-shop-ns.yaml -f complete-demo.yaml

I couldn't access the sock shop ui using nodeip:30001 and not creating end points to access it.

**Comment by scholzj** [comment]
This Kops setup currently creates all cluster nodes in private subnet and single bastion host in public subnet. The nodes in private subnet are not accessible from internet. So you will not be able to do `nodeip:30001` from anywhere. You will be able to do it only from the bastion host or from some other node in the same cluster.

To make it accessible from anywhere, you would need to use a load balancer (either directly with a service with type `Loadbalancer` or through Ingress). But I don't know what exactly does this do microservice demo do any why does it use node port instead of load balancer - so I'm not sure what impact would it have on the application when you change it.

What I can do if it would help you is to add some options to the Ansible tooling which would allow you to setup a public cluster (i.e. without bastion host and with the cluster nodes in public subnets directly accessible from internet). Let me know if you would like to have this feature.

**Comment by coolpalani** [comment]
*Best Regards,*
*Palanisamy*

**Comment by coolpalani** [comment]
I appreciate bastion host kind of approach, but when we deploy application in K8s, we should want access that application as public e.g webserver port 80
Either you make some links for accessing this application endpoints via bastion host dns (since we already created loadbalancer in AWS, we can try to leverage this same for accessing apps with public dns custom port)or create one more approach like public cluster.

**Comment by scholzj** [comment]
Well, the load balancer which is already created is for the access to the Kubernetes API. I would not mix that. When you want to expose something to the internet, you do it normally two ways:
1) Create a service with `Type: Loadbalancer`. That will create a new AWS load balancer for each such service and make it accessible form the internet. This is the easiest way how to do it. But if you have many services it can get a bit more expensive (The classic AWS ELB loadbalancer has some fixed costs even when there is no traffic).
2) You can use Ingress (the Ingress controller is among addons). Ingress will create a single AWS load balancer and use it to route traffic for different addresses (which you can setup for example through Route53). To use Ingress, you should first create a `Type: ClusterIP` service and in addition to it an Ingress resource which will tell Ingress how to do the routing. Ingress is good for HTTP(S) based traffic. It is not that suitable for TCP/UDP traffic.

Additionally, you can do some manual tasks. For example, you can create manually your own AWS Load balancer and configure it to route traffic to different NodePorts.

**Comment by scholzj** [comment]
I added a new parameter `topology`. When set to `public`, it will deploy the cluster to public subnets and use public IP addresses. Such setup can be used to expose the services through NodePorts. Feel free to give it a try and let me know in case of any problems.
